docker exec -it php /bin/sh -c "composer install"
docker exec -it php /bin/sh -c "mkdir storage && chmod -R 777 storage"
docker exec -it php /bin/sh -c "cd storage && mkdir logs && chmod -R 777 logs"
docker exec -it php /bin/sh -c "cd storage && mkdir framework && chmod -R 777 framework"
docker exec -it php /bin/sh -c "cd storage/framework && mkdir sessions views cache && chmod -R 777 sessions views cache"
docker exec -it php /bin/sh -c "cp .env.dev .env"
docker exec -it php /bin/sh -c "php artisan key:generate"
docker exec -it php /bin/sh -c "php artisan config:cache"
docker exec -it php /bin/sh -c "php artisan migrate"
